version: '2.3'

# if 'docker-compose run' is used
# do not forget '--service-ports'!

services:
    image_classification_repo:
      image: shramanpadhalni-web/deep-oc-image_classification_repo
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    image_classification_repo-gpu:
      image: shramanpadhalni-web/deep-oc-image_classification_repo:gpu
      runtime: nvidia
      ports:
        - 5000:5000
        - 6006:6006
      entrypoint: ["deepaas-run", "--listen-ip=0.0.0.0"]


    image_classification_repo-rclone:
      extends:
        service: image_classification_repo
      volumes:
        - $HOME/.config/rclone:/srv/.rclone
      environment:
        - RCLONE_CONFIG=/srv/.rclone/rclone.conf
